version: '3.8'

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /Users/ekoljone/Desktop/Inception/mariadb_data
      o: bind
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      type: none
      device: /Users/ekoljone/Desktop/Inception/wordpress_data
      o: bind

services:
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    image: mariadb-img
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    image: wordpress-img
    env_file: .env
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - mariadb
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-img
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
